<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_api</name>
   <tag></tag>
   <elementGuidId>5d4c16d6-067a-466b-bc6a-009092e19ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div[2]/div[2]/div[1]/div[1]/div/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div[2]/div[2]/div[1]/div[1]/div/div[2]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
